#! /bin/sh
#
# rubypanel.sh
# Copyright (C) 2018 derrick cope <derrick(at)thecopes.me>
#
# Distributed under terms of the MIT license.
#


lemonbar.rb | lemonbar -g 1920x20 -d -B "#333333" -F "#D3D3D3" &

lemonbar.rb | lemonbar -g 1920x20+1920 -d -B "#333333" -F "#D3D3D3" &

